name: CI
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
# https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  release:
    types:
      - published # a release, pre-release, or draft of a release is published
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  SLICE_VERSION: '0.0.1'
  RELEASE_URL: 'https://github.com/atamai-labs/Atamai.Slice'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Set release information
        if: github.event_name == 'release'
        run: |
          echo "SLICE_VERSION=${GITHUB_REF_NAME/#[vV]/}" >> $GITHUB_ENV
          echo "RELEASE_URL=${{ github.event.release.html_url }}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release -p:Version=${SLICE_VERSION} -p:ReleaseUrl=${RELEASE_URL}
      # - name: Test
      #   run: dotnet test --no-build --configuration Release
      - name: Publish release to NuGet
        if: github.event_name == 'release'
        run: |
          dotnet nuget push "**/Atamai.Slice.*SLICE_VERSION.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
          dotnet nuget push "**/Atamai.Slice.*SLICE_VERSION.snupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json